### ISSUE TITLE
Consider adding a very short README with status of the project

### ISSUE THREAD

**Issue by kamalmarhubi** [flier/tokio-kafka#1]
I came across this and it seems promising, but I have no idea how far along it is, what protocol versions it speaks, or anything else. It doesn't need to be more than a couple of bullet points, but it'd be handy to have a README. :-)

**Comment by flier** [comment]
Sure, I will do it later, but it is not finished yet :)

**Comment by pimeys** [comment]
We're later this year moving to Kafka from RabbitMQ, and would be nice to know what's the status of this project and could we actually use it in production?

**Comment by flier** [comment]
Sorry, not yet, it is still a experimental project, but I plan to refactor it later after `tokio` related crates more stable
