### ISSUE TITLE
Getting below compilaton error

### ISSUE THREAD

**Issue by surajprak** [flier/tokio-kafka#18]
error[E0277]: the trait bound `std::sync::Arc<str>: std::convert::From<&str>` is not satisfied
  --> /home/suraj.prakash/.cargo/registry/src/github.com-1ecc6299db9ec823/abstract-ns-0.4.3/src/name.rs:67:23
   |
67 |         Ok(Name(value.into()))
   |                       ^^^^ the trait `std::convert::From<&str>` is not implemented for `std::sync::Arc<str>`
   |
   = help: the following implementations were found:
             <std::sync::Arc<T> as std::convert::From<T>>
   = note: required because of the requirements on the impl of `std::convert::Into<std::sync::Arc<str>>` for `&str`

error: aborting due to previous error

error: Could not compile `abstract-ns`.
warning: build failed, waiting for other jobs to finish...
error: build failed

Could you please suggest a stable commit, which i can use

**Comment by flier** [comment]
what's version of rust you are using?
```
$rustc -V
rustc 1.25.0 (84203cac6 2018-03-25)
```

**Comment by surajprak** [comment]
rustc 1.20.0 (f3d6973f4 2017-08-27)

**Comment by flier** [comment]
seems your rust compiler too old to build `abstract-ns`, you may upgrade with [rustup](https://rustup.rs/)
